fixed typo in run-local and added run-cloud

diff --git a/run-cloud b/run-cloud
--- a/run-cloud
+++ b/run-cloud
@@ -14,11 +14,14 @@
 set -e
 
 # Parse command line arguments
+unset WORK_DIR
 SRC_DIR=.
-WORK_DIR=/tmp/fids-capstone-data
+WORK_DIR=gs://sc-fids-capstone-bucket/fids-capstone-data
 MAX_TARGET_VIDEOS=5
-USE_BEAM=0
-BEAM_RUNNER=DirectRunner
+USE_BEAM=1
+BEAM_RUNNER=DataflowRunner
+PROJECT=$(gcloud config get-value project || echo $PROJECT)
+REGION=us-central1
 while [[ $# -gt 0 ]]; do
   case $1 in
     --src-dir)
@@ -48,6 +51,22 @@ while [[ $# -gt 0 ]]; do
   esac
   shift
 done
+
+if [[ -z $WORK_DIR ]]; then
+  echo "error: argument --work-dir is required"
+  exit 1
+fi
+
+if [[ $WORK_DIR != gs://* ]]; then
+  echo "error: --work-dir must be a Google Cloud Storage path"
+  echo "       example: gs://sc-fids-capstone-bucket/fids-capstone-data"
+  exit 1
+fi
+
+if [[ -z $PROJECT ]]; then
+  echo 'error: --project is required to run in Google Cloud Platform.'
+  exit 1
+fi
 
 # Wrapper function to print the command being run
 function run {
